const LISTINGS = [
  // ── Покупка: студии ──
  { id: 1, deal: "buy", rooms: "studio", district: "Ховрино", type: "новостройка", price: 5.2, area: 28, floor: 12, totalFloors: 25, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 8, address: "ул. Митинская, 28к1", description: "Купил год назад — живу здесь сам. Монолит, 12 этаж, лоджию застеклил сразу. Соседи молодые, тихие. До метро 8 минут — проверял, это реально. Паркинг подземный, взял место в аренду." },
  { id: 2, deal: "buy", rooms: "studio", district: "Ховрино", type: "новостройка", price: 4.1, area: 24, floor: 3, totalFloors: 17, balcony: null, renovation: "no", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 12, address: "ул. Южнобутовская, 14", description: "Студия в новостройке под чистовую отделку. Третий этаж, панель. Без балкона. Наземная парковка есть. До метро 12 минут — ходит автобус." },
  { id: 3, deal: "buy", rooms: "studio", district: "Ховрино", type: "новостройка", price: 6.8, area: 32, floor: 18, totalFloors: 24, balcony: "balcony", renovation: "euro", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 10, address: "ул. Строгинский бул., 7", description: "32 метра на 18-м этаже с балконом и панорамой — для студии это много. Евроремонт, монолит, подземный паркинг. Заехать и жить." },
  { id: 4, deal: "buy", rooms: "studio", district: "Ховрино", type: "новостройка", price: 4.5, area: 26, floor: 7, totalFloors: 20, balcony: "loggia", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 6, address: "ул. Зеленоградская, 33", description: "Брал два года назад, не пожалел. До метро ровно 6 минут — сам замерял. Лоджия большая, поставил шкаф и велосипед влез. Соседи нормальные, тихо." },

  // ── Покупка: 1-комнатные ──
  { id: 5, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 8.5, area: 38, floor: 5, totalFloors: 14, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 7, address: "ул. Люблинская, 165", description: "Однушка, жила семья 12 лет. Косметику делали сами в 2018 году — аккуратно. Балкон застеклён. До метро 7 минут." },
  { id: 6, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 18.5, area: 42, floor: 4, totalFloors: 8, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: "ground", metroTime: 5, address: "Комсомольский пр-т, 36", description: "Кирпичная восьмиэтажка, 4-й этаж. 42 метра, раздельный санузел, евроремонт. Наземная парковка. 5 минут до метро — пешком, без спешки." },
  { id: 7, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 11.2, area: 36, floor: 9, totalFloors: 12, balcony: "loggia", renovation: "cosmetic", houseType: "brick", bathroom: "combined", parking: null, metroTime: 8, address: "ул. Короленко, 7", description: "Прожили здесь 5 лет, дом кирпичный — зимой очень тепло. 9-й этаж, хороший обзор. Лоджия выходит на тихую сторону. Продаём — расширяемся." },
  { id: 8, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 9.8, area: 40, floor: 2, totalFloors: 16, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 10, address: "ул. Профсоюзная, 116к2", description: "Евроремонт делали для себя в 2020 — хорошие материалы, ничего не экономили. Второй этаж, удобно с детьми и пожилыми. Балкон есть, паркинг наземный." },
  { id: 9, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 8.9, area: 34, floor: 1, totalFloors: 9, balcony: null, renovation: "no", houseType: "brick", bathroom: "combined", parking: null, metroTime: 12, address: "Измайловский пр-д, 18", description: "Первый этаж, без балкона, ремонта нет. Дом кирпичный, потолки выше стандарта. Цена честная — под своё обустройство." },
  { id: 10, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 7.4, area: 33, floor: 8, totalFloors: 12, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 5, address: "ул. Полярная, 9к2", description: "5 минут до метро — не преувеличение, проверено. 8 этаж, вид есть. Балкон во двор, детская площадка внизу. Район тихий, магазины рядом." },
  { id: 11, deal: "buy", rooms: 1, district: "Ховрино", type: "новостройка", price: 14.2, area: 44, floor: 15, totalFloors: 30, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 7, address: "ул. Дмитрия Ульянова, 31к1", description: "Однушка 44 м² с раздельным санузлом — почти формат двушки. 15-й этаж монолита, лоджия, евроремонт. Подземный паркинг. 7 минут до метро." },
  { id: 12, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 10.1, area: 37, floor: 6, totalFloors: 14, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 9, address: "ул. Ярцевская, 22", description: "Наша квартира, жили 6 лет. Подъезд чистый, консьерж работает. Балкон большой — сделали хранилку и сушку. Паркинг наземный, место обычно находим." },
  { id: 13, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 9.3, area: 35, floor: 4, totalFloors: 9, balcony: "balcony", renovation: "no", houseType: "brick", bathroom: "combined", parking: null, metroTime: 6, address: "ул. Преображенский Вал, 15", description: "Продаю как есть: старые обои, сантехника родная. Кирпичный дом, 4-й этаж. Балкон есть, не застеклён. Цена ниже рынка именно поэтому." },

  // ── Покупка: 2-комнатные ──
  { id: 14, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 12.5, area: 54, floor: 7, totalFloors: 14, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "separate", parking: null, metroTime: 8, address: "Новочеркасский бул., 20", description: "Наша двушка, живём 4 года. Евроремонт хороший, раздельный санузел — в семье это важно. Балкон большой, летом там обедаем. Продаём — купили трёшку." },
  { id: 15, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 32.0, area: 68, floor: 3, totalFloors: 7, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "separate", parking: "ground", metroTime: 4, address: "ул. Усачёва, 11", description: "Сталинка с дизайнерским ремонтом: потолки 3,2 м, паркет ёлочкой, лепнина восстановлена. 68 метров настоящего пространства. 4 минуты до метро. Таких квартир единицы." },
  { id: 16, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 14.8, area: 52, floor: 5, totalFloors: 9, balcony: "balcony", renovation: "cosmetic", houseType: "brick", bathroom: "separate", parking: null, metroTime: 6, address: "ул. Гарибальди, 23к1", description: "Жили 9 лет, дом кирпичный — слышимость очень низкая. 5 этаж, балкон с видом на двор с деревьями. Двор закрытый, шлагбаум. Продаём — купили загородный дом." },
  { id: 17, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 15.5, area: 62, floor: 20, totalFloors: 25, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 9, address: "ул. Маршала Катукова, 15к1", description: "20-й этаж монолита, двушка 62 метра, вид на несколько кварталов. Евроремонт, раздельный санузел, лоджия. Подземный паркинг. Для тех, кто хочет видеть город." },
  { id: 18, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 28.0, area: 58, floor: 4, totalFloors: 6, balcony: null, renovation: "designer", houseType: "stalinka", bathroom: "separate", parking: null, metroTime: 3, address: "Пятницкая ул., 47", description: "Сталинка, дизайнерский ремонт сделан профессиональной бригадой — есть документы. Без балкона, но окна на тихий переулок. 3 минуты до метро." },
  { id: 19, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 11.9, area: 56, floor: 14, totalFloors: 22, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: "multilevel", metroTime: 7, address: "ул. Генерала Белобородова, 10", description: "Заехали после сдачи дома. ТСЖ работает нормально, подъезды убирают. Многоуровневый паркинг рядом — берём место в аренду. Лоджия большая, летом там обедаем." },
  { id: 20, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 10.8, area: 50, floor: 9, totalFloors: 16, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 11, address: "ул. Академика Варги, 8к1", description: "Двушка в типовой панели, 9 этаж. Косметику делали 4 года назад, живём аккуратно. Балкон застеклён. Наземная парковка. До метро 11 минут — ходит автобус." },
  { id: 21, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 16.3, area: 55, floor: 6, totalFloors: 10, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 7, address: "ул. Сокольническая, 9", description: "Кирпичный дом, 6-й этаж. Двушка 55 метров с раздельным санузлом и евроремонтом. Тихий двор. Балкон на зелёную сторону. Хорошая цена для района." },
  { id: 22, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 10.2, area: 58, floor: 11, totalFloors: 20, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 10, address: "ул. Южнобутовская, 50к1", description: "Новостройка 2021 года. Лоджию застеклили сразу — получилась терраса. Паркинг подземный, место в собственности. Соседи приятные, в чате активные." },
  { id: 23, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 11.5, area: 55, floor: 16, totalFloors: 24, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 5, address: "ул. Дыбенко, 38к7", description: "16-й этаж, евроремонт, раздельный санузел. Двушка 55 метров с лоджией, подземный паркинг. 5 минут до метро. Квартира, в которой всё продумано." },

  // ── Покупка: 3-комнатные ──
  { id: 24, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 45.0, area: 95, floor: 5, totalFloors: 8, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 5, address: "Фрунзенская наб., 40", description: "95 метров сталинки с дизайнерским ремонтом — другая категория жилья. Потолки больше 3 метров, два санузла, паркет. 5-й из 8, рядом с метро. Адрес, который говорит за себя." },
  { id: 25, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 16.5, area: 72, floor: 10, totalFloors: 17, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "separate", parking: "ground", metroTime: 9, address: "ул. Братиславская, 14", description: "Живём 11 лет, до нас — родители. 10 этаж, солнце с утра. Две школы рядом и садик в 5 минутах. Фасад дома недавно обновляли." },
  { id: 26, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 22.0, area: 78, floor: 3, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 5, address: "ул. Кржижановского, 17к2", description: "Кирпичный дом 1971 года. Трёшка 78 метров, евроремонт в 2019 — меняли проводку, трубы, окна. Документы в порядке, юридически чистая." },
  { id: 27, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 17.2, area: 75, floor: 8, totalFloors: 14, balcony: "loggia", renovation: "cosmetic", houseType: "panel", bathroom: "separate", parking: "ground", metroTime: 8, address: "ул. Островитянова, 45к1", description: "Наша семья здесь 15 лет. Соседи давние, не снимают — дом тихий. Школа во дворе. Лоджия выходит на парк, весной особенно красиво." },
  { id: 28, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 42.0, area: 88, floor: 6, totalFloors: 7, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 4, address: "Большая Ордынка, 31", description: "Сталинская трёшка с дизайнерским ремонтом, 4 минуты от метро. 88 метров, два санузла, балкон. Дом исторический, соседи — давние жители района." },
  { id: 29, deal: "buy", rooms: 3, district: "Ховрино", type: "новостройка", price: 28.5, area: 85, floor: 22, totalFloors: 32, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 6, address: "Ленинский пр-т, 95к1", description: "22-й этаж монолита. 85 метров, евроремонт, два санузла, лоджия с видом на город. Подземный паркинг. Квартира для тех, кто выбирает высоту и комфорт без компромиссов." },
  { id: 30, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 14.8, area: 68, floor: 1, totalFloors: 9, balcony: "balcony", renovation: "cosmetic", houseType: "brick", bathroom: "separate", parking: null, metroTime: 10, address: "Измайловский бул., 50", description: "Первый этаж — цена соответствующая. Решётки на окнах есть. Дом кирпичный, тёплый. Трёшка 68 метров, балкон, косметический ремонт." },
  { id: 31, deal: "buy", rooms: 3, district: "Ховрино", type: "новостройка", price: 23.0, area: 82, floor: 19, totalFloors: 25, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 8, address: "ул. Таллинская, 5к2", description: "Покупали два года назад. Монолит — тишина отличная, соседей почти не слышно. 19 этаж, два санузла. Паркинг удобный. Продаём — меняем город." },
  { id: 32, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 18.5, area: 74, floor: 12, totalFloors: 16, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "separate", parking: "ground", metroTime: 7, address: "ул. Молодогвардейская, 36к2", description: "Трёшка 74 метра с евроремонтом, 12-й этаж. Хороший вид, светло, тихо. Раздельный санузел, балкон, наземный паркинг. Готова к заезду." },
  { id: 33, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 15.9, area: 70, floor: 4, totalFloors: 9, balcony: "balcony", renovation: "cosmetic", houseType: "brick", bathroom: "separate", parking: null, metroTime: 5, address: "Большая Черкизовская, 22", description: "Кирпичный дом, жили здесь 8 лет. Дворик маленький, но уютный. Трёшка с раздельным санузлом, 4 этаж — удобно. Школа и поликлиника через квартал." },
  { id: 34, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 13.0, area: 65, floor: 7, totalFloors: 12, balcony: "loggia", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 6, address: "ул. Широкая, 3к2", description: "Продаю трёшку, жил сам. Совмещённый санузел, лоджия, 7-й этаж. Косметику делал своими руками в 2017 — аккуратно. Парковки нет, но двор большой." },

  // ── Покупка: 4-комнатные ──
  { id: 35, deal: "buy", rooms: 4, district: "Ховрино", type: "вторичка", price: 65.0, area: 130, floor: 4, totalFloors: 7, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 6, address: "ул. Тимура Фрунзе, 11", description: "130 метров сталинки с дизайнерским ремонтом. Потолки, лепнина, паркет, два санузла. 4-й этаж, балкон, наземная парковка. Для тех, кто знает чего хочет." },
  { id: 36, deal: "buy", rooms: 4, district: "Ховрино", type: "вторичка", price: 58.0, area: 120, floor: 5, totalFloors: 6, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 3, address: "Кадашёвская наб., 14", description: "120 метров сталинки, 3 минуты от метро. Дизайнерский ремонт с уважением к истории — сохранены потолки, восстановлен паркет. Четыре комнаты, два санузла." },
  { id: 37, deal: "buy", rooms: 4, district: "Ховрино", type: "новостройка", price: 42.0, area: 115, floor: 25, totalFloors: 33, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 7, address: "ул. Вавилова, 81к1", description: "25-й этаж — горизонт виден буквально. 115 метров с евроремонтом, 4 комнаты, два санузла, лоджия, подземный паркинг. Квартира, которую не нужно улучшать." },
  { id: 38, deal: "buy", rooms: 4, district: "Ховрино", type: "вторичка", price: 35.0, area: 105, floor: 8, totalFloors: 14, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "two_plus", parking: "ground", metroTime: 5, address: "ул. Каховка, 18к2", description: "Наша семья здесь 12 лет, дети выросли. Кирпичный дом, 8 этаж, четыре отдельные комнаты — каждому своя. Два санузла, огромный балкон. Очень не хочется уезжать." },

  // ── Покупка: 5+ комнатные ──
  { id: 39, deal: "buy", rooms: 5, district: "Ховрино", type: "вторичка", price: 85.0, area: 170, floor: 3, totalFloors: 5, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 4, address: "Пречистенская наб., 29", description: "170 метров сталинки с дизайнерским ремонтом. Пять комнат, высокие потолки, два санузла, балкон. 4 минуты до метро. Для большой семьи или нескольких поколений под одной крышей." },
  { id: 40, deal: "buy", rooms: 6, district: "Ховрино", type: "вторичка", price: 95.0, area: 200, floor: 4, totalFloors: 6, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 5, address: "ул. Бахрушина, 28", description: "200 метров сталинки. Шесть комнат, дизайнерский ремонт, исторический дом. 5 минут пешком до метро. Предложение без аналогов в текущей базе." },

  // ── Покупка: без ремонта / черновая ──
  { id: 41, deal: "buy", rooms: 1, district: "Ховрино", type: "новостройка", price: 5.8, area: 38, floor: 4, totalFloors: 22, balcony: "loggia", renovation: "no", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 14, address: "ул. Южнобутовская, 69к1", description: "Монолит, черновая отделка — делайте под себя. 4 этаж, лоджия большая. Паркинг подземный. До метро 14 минут, но есть маршрутка — быстрее." },
  { id: 42, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 9.5, area: 52, floor: 10, totalFloors: 20, balcony: "loggia", renovation: "no", houseType: "monolith", bathroom: "combined", parking: "multilevel", metroTime: 8, address: "ул. Левобережная, 4к14", description: "Двушка под отделку в монолите, 2024 год. Документы готовы. Многоуровневый паркинг рядом. Цена ниже именно потому что без ремонта — делаете сами, под себя." },
  { id: 43, deal: "buy", rooms: 3, district: "Ховрино", type: "новостройка", price: 14.0, area: 78, floor: 6, totalFloors: 18, balcony: "loggia", renovation: "no", houseType: "panel", bathroom: "separate", parking: "underground", metroTime: 10, address: "Пятницкое ш., 21", description: "Трёшка без отделки в новостройке. Раздельный санузел, лоджия, паркинг подземный. Цена снижена в сравнении с готовыми квартирами в этом доме." },

  // ── Покупка: дорогие с дизайнерским ремонтом ──
  { id: 44, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 38.0, area: 72, floor: 6, totalFloors: 8, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 3, address: "ул. Льва Толстого, 8", description: "Сталинка в 3 минутах от метро, дизайнерский ремонт, два санузла. 72 метра, балкон, 6-й этаж. Приехать с чемоданом — и жить." },
  { id: 45, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 55.0, area: 100, floor: 3, totalFloors: 5, balcony: null, renovation: "designer", houseType: "brick", bathroom: "two_plus", parking: null, metroTime: 5, address: "Лаврушинский пер., 11", description: "100 метров в кирпичном доме, дизайнерский ремонт с авторской концепцией. Три комнаты, два санузла, потолки выше 3 метров. 5 минут до метро тихим переулком." },

  // ── Покупка: панельные бюджетные ──
  { id: 46, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 6.5, area: 32, floor: 1, totalFloors: 9, balcony: "balcony", renovation: "no", houseType: "panel", bathroom: "combined", parking: null, metroTime: 15, address: "ул. Поляны, 9", description: "Первый этаж, без ремонта, 15 минут до метро. Всё это в цене. Балкон есть. Подойдёт под покупку с минимальными вложениями или под ремонт и сдачу." },
  { id: 47, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 9.2, area: 45, floor: 5, totalFloors: 9, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 8, address: "ул. Грёкова, 10", description: "Панелька советская, но ухоженная — управляйка нормальная, подъезд красят каждый год. Двушка небольшая, но планировка удобная. Рядом рынок и «Пятёрочка»." },
  { id: 48, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 9.8, area: 48, floor: 3, totalFloors: 12, balcony: "loggia", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 12, address: "ул. Тёплый Стан, 7к1", description: "Жили 6 лет с ребёнком. Лоджия большая — зимой хранение, летом цветы. Двор закрытый, дети гуляют спокойно. Школа хорошая в квартале." },
  { id: 49, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 11.0, area: 60, floor: 2, totalFloors: 9, balcony: "balcony", renovation: "no", houseType: "panel", bathroom: "combined", parking: null, metroTime: 10, address: "ул. Петрозаводская, 22", description: "Трёшка без ремонта, 2-й этаж. Три изолированные комнаты. Балкон есть. Дом 1978 года, лифт недавно меняли. Продаём быстро, торг уместен." },

  // ── Покупка: высокие этажи, видовые ──
  { id: 50, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 18.0, area: 65, floor: 24, totalFloors: 25, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 7, address: "ул. Маршала Катукова, 24к2", description: "Предпоследний этаж — вид без помех. 65 метров, евроремонт, раздельный санузел, лоджия. Подземный паркинг. Двушка, где каждое утро начинается с панорамы." },
  { id: 51, deal: "buy", rooms: 3, district: "Ховрино", type: "новостройка", price: 35.0, area: 90, floor: 30, totalFloors: 33, balcony: "loggia", renovation: "designer", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 5, address: "Ленинский пр-т, 111к1", description: "30-й этаж — Москва у ваших ног. 90 метров с дизайнерским ремонтом, три комнаты, два санузла, лоджия. Монолит, подземный паркинг. 5 минут до метро." },
  { id: 52, deal: "buy", rooms: 1, district: "Ховрино", type: "новостройка", price: 8.2, area: 40, floor: 22, totalFloors: 24, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 4, address: "ул. Дыбенко, 36к3", description: "Купил на 22 этаже и ни разу не пожалел. Лоджия огромная, утром там кофе с видом на Москву. 4 минуты до метро. Продаю потому что женился — нужна двушка." },

  // ── Аренда: студии ──
  { id: 53, deal: "rent", rooms: "studio", district: "Ховрино", type: "новостройка", price: 35, area: 26, floor: 8, totalFloors: 20, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: null, metroTime: 9, address: "ул. Митинская, 40к1", description: "Студия в новостройке — 8-й этаж, лоджия, аккуратный ремонт. 9 минут до метро пешком. Для одного или пары: всё под рукой, ничего лишнего." },
  { id: 54, deal: "rent", rooms: "studio", district: "Ховрино", type: "новостройка", price: 28, area: 24, floor: 14, totalFloors: 22, balcony: null, renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: "underground", metroTime: 12, address: "ул. Южнобутовская, 117", description: "Сдаю студию, покупал для сдачи. Техника новая, сантехника без проблем. 14-й этаж, вид на город. Паркинг подземный — обсуждаем отдельно." },
  { id: 55, deal: "rent", rooms: "studio", district: "Ховрино", type: "новостройка", price: 40, area: 30, floor: 10, totalFloors: 18, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "combined", parking: null, metroTime: 7, address: "ул. Миклухо-Маклая, 55к1", description: "Снимал год — отличное место. Хозяева адекватные, ремонт хороший. Лоджия на тихий двор. 7 минут до метро — проверял каждый день. Переезжаю в другой район." },

  // ── Аренда: 1-комнатные ──
  { id: 56, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 40, area: 36, floor: 3, totalFloors: 14, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 8, address: "ул. Перерва, 54", description: "Снимал год. Хозяйка пожилая, понимающая — ни разу не беспокоила без причины. Ремонт простой, но чистый. Балкон большой. Соседи нормальные." },
  { id: 57, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 80, area: 40, floor: 5, totalFloors: 8, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 5, address: "ул. Россолимо, 6", description: "Кирпичный дом, евроремонт, раздельный санузел — в аренде такое редко. 40 метров, 5-й этаж из восьми, балкон. 5 минут до метро. Квартира для тех, кто ценит качество." },
  { id: 58, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 55, area: 35, floor: 7, totalFloors: 12, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "combined", parking: null, metroTime: 6, address: "ул. Русаковская, 31", description: "Сдаю однушку в кирпичном доме. Евроремонт делал три года назад, всё аккуратно. Мебель нормальная, техника работает. Животных нельзя. Залог один месяц." },
  { id: 59, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 42, area: 38, floor: 9, totalFloors: 16, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 9, address: "ул. Профсоюзная, 132к4", description: "Снимаю уже 2 года — менять не собираюсь. Хозяева отзывчивые. Балкон на 9-м этаже, вечером красиво. Район тихий, двор большой — собаку выгуливать удобно." },
  { id: 60, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 38, area: 33, floor: 4, totalFloors: 9, balcony: null, renovation: "cosmetic", houseType: "brick", bathroom: "combined", parking: null, metroTime: 10, address: "Первомайская ул., 42", description: "Аккуратная однушка в кирпичном доме. Без балкона, но окна на тихую сторону. Мебель и техника есть. Без курения в квартире." },
  { id: 61, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 35, area: 32, floor: 6, totalFloors: 12, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 7, address: "ул. Молодцова, 25к2", description: "Снимаю полгода. Бюджетно, зато чистый ремонт и хозяева не докучают. Балкон есть. 7 минут до метро — хожу пешком каждый день." },
  { id: 62, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 45, area: 34, floor: 2, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "combined", parking: null, metroTime: 5, address: "ул. Большая Черкизовская, 8", description: "Евроремонт в кирпичном доме, 5 минут до метро. 2-й этаж — никаких ожиданий лифта. Удобно с велосипедом или самокатом. Балкон есть." },
  { id: 63, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 48, area: 37, floor: 11, totalFloors: 14, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 8, address: "ул. Ярцевская, 14", description: "Сдаю квартиру дочери, переехала. Евроремонт 2022. 11 этаж, тихо, вид хороший. Парковка наземная. Долгосрочно, семью или пару." },
  { id: 64, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 55, area: 40, floor: 8, totalFloors: 14, balcony: "loggia", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 6, address: "ул. Кедрова, 15", description: "Редкость в аренде: кирпич, евроремонт, раздельный санузел, лоджия. 40 метров, 8-й этаж. 6 минут до метро. Выше большинства предложений в этом бюджете." },
  { id: 65, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 33, area: 34, floor: 5, totalFloors: 12, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 13, address: "Новоясеневский пр-т, 12к2", description: "Снимаю год. До метро 13 минут — далековато, знаю. Зато тихо, двор зелёный, парковок вдоволь. Хозяева молодые, понимающие — кран починили на следующий день." },
  { id: 66, deal: "rent", rooms: 1, district: "Ховрино", type: "новостройка", price: 45, area: 38, floor: 18, totalFloors: 24, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "combined", parking: "underground", metroTime: 5, address: "ул. Дыбенко, 40к2", description: "18-й этаж новостройки — пространство и свет. Евроремонт, лоджия, подземный паркинг. 5 минут до метро. Современная квартира без лишних деталей." },

  // ── Аренда: 2-комнатные ──
  { id: 67, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 55, area: 50, floor: 6, totalFloors: 14, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "separate", parking: null, metroTime: 7, address: "ул. Люблинская, 169", description: "Снимаем с женой 3 года. Раздельный санузел — это важно, цените. Балкон большой, поставили гамак. Район хороший: кафе, магазины. Хозяйка адекватная." },
  { id: 68, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 120, area: 65, floor: 4, totalFloors: 7, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "separate", parking: null, metroTime: 4, address: "ул. Плющиха, 22", description: "Сталинка с дизайнерским ремонтом в аренду — такое бывает редко. 65 метров, раздельный санузел, балкон, 4 минуты до метро. Для тех, кто не идёт на компромиссы." },
  { id: 69, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 65, area: 52, floor: 3, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 6, address: "ул. Вавилова, 48к1", description: "Сдаю двушку в кирпичном доме. Евроремонт делал сам три года назад, всё аккуратно. Раздельный санузел. Без домашних животных." },
  { id: 70, deal: "rent", rooms: 2, district: "Ховрино", type: "новостройка", price: 70, area: 60, floor: 15, totalFloors: 25, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 8, address: "ул. Исаковского, 20к1", description: "Двушка 60 метров на 15-м этаже в монолите — вид, тишина, современный евроремонт. Раздельный санузел, лоджия, подземный паркинг. Для тех, кто привык к комфорту." },
  { id: 71, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 110, area: 55, floor: 3, totalFloors: 5, balcony: null, renovation: "designer", houseType: "stalinka", bathroom: "separate", parking: null, metroTime: 3, address: "Климентовский пер., 6", description: "3 минуты от метро, сталинка с дизайнерским ремонтом. 55 метров, два отдельных санузла. Без балкона — зато тихий переулок и двор с вековыми липами." },
  { id: 72, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 50, area: 54, floor: 10, totalFloors: 17, balcony: "loggia", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 8, address: "Митинская ул., 12", description: "Снимаем семьёй год. 10 этаж, вид на парк — осенью особенно красиво. Лоджия большая, сделали зону для ребёнка. Хозяин пунктуальный, на звонки отвечает быстро." },
  { id: 73, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 48, area: 48, floor: 7, totalFloors: 12, balcony: "balcony", renovation: "cosmetic", houseType: "panel", bathroom: "combined", parking: null, metroTime: 11, address: "ул. Академика Варги, 21", description: "Сдаю двушку, жили сами. Косметика нормальная, мебель есть. Балкон застеклён. До метро 11 минут, но автобус ходит часто. Долгосрочно." },
  { id: 74, deal: "rent", rooms: 2, district: "Ховрино", type: "новостройка", price: 52, area: 56, floor: 12, totalFloors: 20, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 10, address: "Бутовский бул., 7", description: "Снимали год с партнёром. Лоджия выходит на спортплощадку, по утрам приятно смотреть. Паркинг подземный — зимой особенно ценишь. Переезжаем поближе к работе." },
  { id: 75, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 55, area: 50, floor: 8, totalFloors: 16, balcony: "loggia", renovation: "euro", houseType: "panel", bathroom: "combined", parking: "ground", metroTime: 7, address: "ул. Островитянова, 19к2", description: "Сдаю двушку с евроремонтом 2021 года. Мебель, техника, посуда — всё есть, заезжайте с вещами. Лоджия застеклённая. Паркинг наземный. Долгосрочно, без животных." },

  // ── Аренда: 3-комнатные ──
  { id: 76, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 180, area: 90, floor: 5, totalFloors: 8, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 5, address: "Зубовский бул., 16", description: "Сталинская трёшка с дизайнерским ремонтом: просторные комнаты, высокие потолки, два санузла, балкон. 5 минут от метро. Для тех, кто готов платить за качество жизни." },
  { id: 77, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 70, area: 70, floor: 9, totalFloors: 17, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "separate", parking: "ground", metroTime: 8, address: "ул. Братиславская, 26к1", description: "Снимаем с семьёй два года. Трёшка — хватает с запасом. Дети ходят в школу во дворе. 9 этаж, балкон, вид на зелёный квартал. Хозяева нормальные." },
  { id: 78, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 90, area: 75, floor: 6, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 5, address: "ул. Архитектора Власова, 18", description: "Кирпичный дом, трёшка с евроремонтом и раздельным санузлом. 75 метров, 6-й этаж, балкон. 5 минут до метро. Квартира для семьи, которая ценит пространство." },
  { id: 79, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 160, area: 85, floor: 4, totalFloors: 6, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 4, address: "Ордынский тупик, 3", description: "Жили год — один из лучших адресов где доводилось снимать. Сталинка, потолки больше трёх метров, два санузла. 4 минуты до метро — иногда дольше одеться. Тихий двор с соснами." },
  { id: 80, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 85, area: 78, floor: 10, totalFloors: 14, balcony: "loggia", renovation: "euro", houseType: "brick", bathroom: "separate", parking: "ground", metroTime: 6, address: "ул. Шверника, 10", description: "Сдаю трёшку в кирпичном доме. 10 этаж, лоджия. Евроремонт делали для себя — хорошие материалы. Раздельный санузел. Парковка наземная во дворе." },
  { id: 81, deal: "rent", rooms: 3, district: "Ховрино", type: "вторичка", price: 75, area: 68, floor: 5, totalFloors: 10, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 7, address: "Сокольнический Вал, 28", description: "Снимали с семьёй. Каждая комната отдельная. Район уютный — кофейни, пекарня, рынок в пяти минутах. Балкон во двор, утром там хорошо с кофе." },
  { id: 82, deal: "rent", rooms: 3, district: "Ховрино", type: "новостройка", price: 95, area: 80, floor: 20, totalFloors: 25, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 9, address: "ул. Таллинская, 7к1", description: "20-й этаж, три комнаты, два санузла, лоджия с видом на город. Евроремонт в монолитном доме, подземный паркинг. Аренда для тех, кто привык к лучшему." },

  // ── Аренда: 4-комнатные ──
  { id: 83, deal: "rent", rooms: 4, district: "Ховрино", type: "вторичка", price: 250, area: 120, floor: 3, totalFloors: 7, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 4, address: "Хамовнический Вал, 26", description: "120 метров сталинки в аренду с дизайнерским ремонтом. Четыре комнаты, два санузла, 4 минуты от метро. Двор закрытый, наземная парковка. Для семьи или тех, кто умеет жить в пространстве." },
  { id: 84, deal: "rent", rooms: 4, district: "Ховрино", type: "вторичка", price: 200, area: 110, floor: 5, totalFloors: 6, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: null, metroTime: 3, address: "Старомонетный пер., 22", description: "Четырёхкомнатная сталинка с авторским ремонтом, 3 минуты от метро. 110 метров, высокие потолки, два санузла. Для большой семьи без компромиссов с качеством жизни." },

  // ── Покупка: кирпичные, близко к метро ──
  { id: 85, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 15.5, area: 50, floor: 3, totalFloors: 5, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 3, address: "ул. Сокольнический Вал, 40", description: "Кирпичная пятиэтажка. Двушка 50 метров, евроремонт, раздельный санузел. 3 минуты до метро — считали шаги. Документы готовы, продаём быстро." },
  { id: 86, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 12.0, area: 38, floor: 7, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "combined", parking: null, metroTime: 4, address: "ул. Гарибальди, 10", description: "Покупал для себя 4 года назад. Кирпич, 7 этаж из 9 — тихо, вид хороший. Евроремонт делал своими руками (плиточника нанимал). 4 минуты до метро — ходил каждый день." },
  { id: 87, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 13.8, area: 52, floor: 5, totalFloors: 9, balcony: "balcony", renovation: "euro", houseType: "brick", bathroom: "separate", parking: null, metroTime: 4, address: "ул. Суворовская, 32", description: "Кирпичная двушка в 4 минутах от метро. Евроремонт, раздельный санузел, балкон. 5-й этаж, 52 метра. Такие предложения в этом районе не ждут." },

  // ── Аренда: бюджетные ──
  { id: 88, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 25, area: 30, floor: 1, totalFloors: 9, balcony: null, renovation: "no", houseType: "panel", bathroom: "combined", parking: null, metroTime: 15, address: "ул. Брусилова, 27к2", description: "Сдаю без ремонта. Первый этаж, без балкона. Мебель минимальная есть. 15 минут до метро — цена соответствует." },
  { id: 89, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 28, area: 31, floor: 2, totalFloors: 9, balcony: "balcony", renovation: "no", houseType: "panel", bathroom: "combined", parking: null, metroTime: 14, address: "Новоясеневский пр-т, 32к2", description: "Сдаю честно: без ремонта, старая мебель, 14 минут до метро. Зато чисто, тараканов нет, соседи тихие. Для тех, кому важна цена." },
  { id: 90, deal: "rent", rooms: "studio", district: "Ховрино", type: "новостройка", price: 30, area: 22, floor: 19, totalFloors: 24, balcony: null, renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: null, metroTime: 6, address: "ул. Зеленоградская, 17к3", description: "Снимал год — 19 этаж, ночью вся Москва видна. Маленькая, 22 метра, но мне хватало: работал много, дома только спал. Новый дом, лифт быстрый, соседей не слышно." },

  // ── Аренда: дорогие ──
  { id: 91, deal: "rent", rooms: 2, district: "Ховрино", type: "вторичка", price: 150, area: 70, floor: 6, totalFloors: 8, balcony: "balcony", renovation: "designer", houseType: "stalinka", bathroom: "two_plus", parking: "ground", metroTime: 3, address: "ул. Остоженка, 37/7", description: "3 минуты до метро, сталинка с дизайнерским ремонтом, два санузла, 70 метров. Балкон на тихую улицу. Аренда в этом доме — редкость." },
  { id: 92, deal: "rent", rooms: 1, district: "Ховрино", type: "вторичка", price: 95, area: 45, floor: 3, totalFloors: 6, balcony: null, renovation: "designer", houseType: "stalinka", bathroom: "separate", parking: null, metroTime: 4, address: "Пятницкий пер., 8", description: "Сталинская однушка с дизайнерским ремонтом: 45 метров, потолки 3+ метра, раздельный санузел. Без балкона, зато 4 минуты до метро и атмосфера, которой нет в новостройке." },

  // ── Покупка: новостройки монолит ──
  { id: 93, deal: "buy", rooms: 2, district: "Ховрино", type: "новостройка", price: 16.0, area: 60, floor: 17, totalFloors: 24, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 8, address: "ул. Рябиновая, 2к1", description: "Купили два года назад. Монолит — слышимость низкая. 17 этаж, лоджия большая. Раздельный санузел, место в паркинге в собственности. Продаём — купили частный дом." },
  { id: 94, deal: "buy", rooms: 1, district: "Ховрино", type: "новостройка", price: 8.0, area: 40, floor: 12, totalFloors: 18, balcony: "loggia", renovation: "cosmetic", houseType: "monolith", bathroom: "combined", parking: "multilevel", metroTime: 10, address: "ул. Генерала Тюленева, 4Ак1", description: "Покупал для сдачи — арендаторы жили 2 года без проблем. Лоджия большая. Многоуровневый паркинг рядом, место не куплено. Продаю сейчас." },

  // ── Покупка: первый этаж ──
  { id: 95, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 10.5, area: 48, floor: 1, totalFloors: 9, balcony: null, renovation: "cosmetic", houseType: "brick", bathroom: "combined", parking: null, metroTime: 11, address: "Измайловский бул., 71", description: "Первый этаж. Дом кирпичный, зимой тепло. Двушка 48 метров, без балкона, окна во двор — там тихо. Ремонт нормальный. Цена с учётом этажа." },
  { id: 96, deal: "buy", rooms: 1, district: "Ховрино", type: "вторичка", price: 6.8, area: 31, floor: 1, totalFloors: 12, balcony: "balcony", renovation: "no", houseType: "panel", bathroom: "combined", parking: null, metroTime: 9, address: "ул. Полярная, 3к1", description: "Продаю как есть: без ремонта, первый этаж. Балкон есть, не застеклён. Дом 1985 года. Покупатель делает всё под себя. Торг при осмотре." },

  // ── Аренда: с подземным паркингом ──
  { id: 97, deal: "rent", rooms: 2, district: "Ховрино", type: "новостройка", price: 75, area: 58, floor: 14, totalFloors: 28, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "separate", parking: "underground", metroTime: 6, address: "ул. Дмитрия Ульянова, 42", description: "Двушка 58 метров на 14-м этаже в монолите. Евроремонт, раздельный санузел, лоджия. Подземный паркинг включён. 6 минут до метро. Въезжайте." },
  { id: 98, deal: "rent", rooms: 3, district: "Ховрино", type: "новостройка", price: 100, area: 82, floor: 16, totalFloors: 24, balcony: "loggia", renovation: "euro", houseType: "monolith", bathroom: "two_plus", parking: "underground", metroTime: 7, address: "ул. Рябиновая, 6к2", description: "Снимали семьёй год. Три комнаты в монолите — дети не слышат соседей. Два санузла — утром без очередей. Лоджия, паркинг, 7 минут до метро. Переезжаем в свою квартиру." },

  // ── Покупка: последний этаж ──
  { id: 99, deal: "buy", rooms: 2, district: "Ховрино", type: "вторичка", price: 11.8, area: 52, floor: 14, totalFloors: 14, balcony: "balcony", renovation: "euro", houseType: "panel", bathroom: "separate", parking: null, metroTime: 7, address: "ул. Люблинская, 171к2", description: "Живём на последнем этаже 6 лет — ни разу не пожалели. Крышу меняли в 2022, с тех пор ничего. Вид классный, особенно вечером. Балкон большой, летом там обедаем. Раздельный санузел — в семье важно." },
  { id: 100, deal: "buy", rooms: 3, district: "Ховрино", type: "вторичка", price: 19.5, area: 76, floor: 16, totalFloors: 16, balcony: "loggia", renovation: "euro", houseType: "panel", bathroom: "separate", parking: "ground", metroTime: 6, address: "ул. Островитянова, 53к1", description: "Последний этаж — значит никто сверху не ходит. Трёшка 76 метров с евроремонтом, раздельный санузел, лоджия с открытым видом. 6 минут до метро, наземный паркинг." },
]

// CommonJS export (для Node.js тестов)
if (typeof module !== 'undefined') {
  module.exports = { LISTINGS }
}
